[package]
name = "spotify"
version = "0.7.1"
authors = ["Splitty <splittydev@gmail.com>"]
description = "Easy to use Spotify Local API abstractions."
readme = "README.md"
repository = "https://github.com/SplittyDev/spotify-rs"
documentation = "https://docs.rs/spotify"
keywords = ["Spotify", "API"]
license = "MIT"
edition = "2018"

[lib]
name = "spotify"
path = "src/lib.rs"

[dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"
reqwest = "0.11.*"
hyper = "0.*"
json = "0.11.2"
time = "0.1.35"
